name       : haskell-regex-posix
version    : 0.96.0.0
release    : 5
source     :
    - https://hackage.haskell.org/package/regex-posix-0.96.0.0/regex-posix-0.96.0.0.tar.gz : 251300f1a6bb2e91abb8bf513a21981f8fab79c98a65acea2bb6d6a524414521
license    : BSD-3-Clause
component  : programming.haskell
summary    : The posix regex backend for regex-base
description: |
    The posix regex backend for regex-base
builddeps  :
    - haskell-cabal-install
    - haskell-regex-base-devel
rundeps    :
    - devel:
        - haskell-regex-base-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
