name       : haskell-regex-posix
version    : 0.96.0.1
release    : 6
source     :
    - https://hackage.haskell.org/package/regex-posix-0.96.0.1/regex-posix-0.96.0.1.tar.gz : c7827c391919227711e1cff0a762b1678fd8739f9c902fc183041ff34f59259c
license    : BSD-3-Clause
component  : programming.haskell
summary    : The posix regex backend for regex-base
description: |
    The posix regex backend for regex-base
builddeps  :
    - ghc-devel
    - haskell-regex-base-devel
rundeps    :
    - devel :
        - haskell-regex-base-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
