name       : haskell-regex-posix
version    : 0.95.2
release    : 1
source     :
    - http://hackage.haskell.org/package/regex-posix-0.95.2/regex-posix-0.95.2.tar.gz : 56019921cd4a4c9682b81ec614236fea816ba8ed8785a1640cd66d8b24fc703e
license    : BSD-3-Clause
component  : programming
summary    : The posix regex backend for regex-base
description: |
    The posix regex backend for regex-base
builddeps  :
    - ghc
    - haskell-regex-base
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 regex-posix-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/regex-posix-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/regex-posix-$version/*.a
