name       : haskell-regex-posix
version    : 0.95.2
release    : 3
source     :
    - http://hackage.haskell.org/package/regex-posix-0.95.2/regex-posix-0.95.2.tar.gz : 56019921cd4a4c9682b81ec614236fea816ba8ed8785a1640cd66d8b24fc703e
license    : BSD-3-Clause
component  : programming.haskell
summary    : The posix regex backend for regex-base
description: |
    The posix regex backend for regex-base
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-regex-base
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
